### ISSUE TITLE
Retry failed updates

### ISSUE THREAD

**Issue by JohannesDev** [Heavybullets8/heavy_script#136]
A recent update of photoprism failed. Now I wanted to manually retry the update (maybe with a longer timeout) but heavyscript is always skipping the previously failed version with the following output:
```
photoprism
Skipping previously failed version
231011_16.0.3
```
This can of course make sense as the default behaviour but is there any way to force heavscript to retry the update? I couldn't find anything in the documentation. 
In any case, I still want to thank you so much for this amazing tool. It is a true breeze now to keep all my apps up to date.

**Comment by heavybullets8** [comment]
You can remove the line of the failed application from the "failed" file within heavyscripts directory. 
```bash
nano ~/heavy_script/failed
```

Or, delete the entire file
```bash
rm ~/heavy_script/failed 
```

After which, when heavyscript checks to see if the version of the application is the same version it previously failed on, is no longer there, it will continue with the update.

However, usually when updates fail, its due to breaking changes from upstream, so there is no guarantee that the update will succeed the second time around.

**Comment by JohannesDev** [comment]
Alright, thank you so much!

**Comment by heavybullets8** [comment]
Yeah no problem, I'll go ahead and close this now, open it again if you have more questions regarding that feature
