### ISSUE TITLE
 functions/misc.sh: line 175: export: patchv22120: not a function

### ISSUE THREAD

**Issue by gezuka77** [Heavybullets8/heavy_script#35]
Hi,

I am getting 
` functions/misc.sh: line 175: export: patchv22120: not a function` on both of my  TrueNAS-SCALE-22.02.4 boxes.

**Comment by heavybullets8** [comment]
@gezuka77 
Thanks for the report!

This has been fixed in the latest release, please update Heavyscript with `bash heavy_script.sh --self-update` or run the update with the menu, option 5.

Fixed version: 
v1.1.10
https://github.com/Heavybullets8/heavy_script/releases/tag/v1.1.10

Commit:
https://github.com/Heavybullets8/heavy_script/commit/d50290ba21eff21f9a37632e9fa03cba995a521c
