### ISSUE TITLE
DNS List - broken colors

### ISSUE THREAD

**Issue by smitty-exos** [Heavybullets8/heavy_script#68]
I have 1.5.1 running on test instance and all seemed well.

Building up a new box, and have a couple apps running (sonarr, traefik), however DNS List is only showing 1 DNS/app visible...sonarr is blacked out and can't be read on the screen

App Name  DNS Name                              Port
sonarr    sonarr.ix-sonarr.svc.cluster.local    8989  <- This is there, you just can't read it on the screen
traefik   traefik.ix-traefik.svc.cluster.local  9000

Looking at functions/dns.sh , you are alternating colors, and 1 of them is black (033[1;30m). Lots of people use black background and this gives the illusion that there is nothing there, especially if only a couple apps installed.

I would prefer the header to be say Cyan and all the apps the same color and do away with the alternating row colors. Or at the very least, make them colors that could be displayed in black or white backgrounds :)

All in all a great script though!

**Comment by heavybullets8** [comment]
@smitty-exos This is how it is shown on my terminal. I honestly mistaken the color for gray. 
![image](https://user-images.githubusercontent.com/20793231/217684553-66ca3b10-d78f-4ba7-8d70-9ab356014a9d.png)

I was wanting to stick with alternating colors, in the same way that spreadsheets are made for easier readability. 
If you have any suggestions on two colors to use let me know. Otherwise I will be working on a fix here tonight if I have time.

**Comment by heavybullets8** [comment]
@smitty-exos 
I pushed a new branch to change the color to a different version of gray. In both of my terminals it looks okay. It is just a very slight difference in colors. 

Do you mind checking this branch out and running the dns function and let me know if that will work for now?

If so, you can change branches by:

1. Going to the HeavyScript menu `heavyscript`
2. Choose option 4 `HeavyScript Options`
3. Choose option 2 `Choose Branch`
4. dns-color-hotfix

Then go ahead and run the DNS function again, If this works I will go ahead and change the "gray" variable as well..

**Comment by smitty-exos** [comment]
Excellent! All is working and is very visible now. Thanks!
![image](https://user-images.githubusercontent.com/35970582/217847901-ad108d2d-a873-4176-8bc9-0fb4d00d9a73.png)

**Comment by heavybullets8** [comment]
@smitty-exos 
All is fixed, https://github.com/Heavybullets8/heavy_script/releases/tag/v1.6.1

You can either change branches now, or wait until your next cron job runs, since the branch is deleted `--self-update` (if used) will automatically switch to the latest tag.

I will also have to work on different header colors, but right now its not possible while using the column command. 

Anyway, thank you for the report!
