### ISSUE TITLE
Feature to enable remote api

### ISSUE THREAD

**Issue by terafirmanz** [Heavybullets8/heavy_script#93]
Hi, Truetool had a feature allowing you to enable the k3s api allowing access by external tools like Lens. Will this feature come to heavy_script?

**Comment by heavybullets8** [comment]
Not unless:
1. Someone can implement it
or
2. Someone can show me the old code from Truetool.

The primary focus of heavy_script is to handle Native and Truecharts applications, and it does not encompass all aspects of k3s. However, if someone has access to the old code or is willing to implement the feature, I am open to maintaining it in the project.

Note:
If someone does want to implement it themselves, they will need to get in contact with me so we can include it on the args branch, it will NOT be accepted on main. Since I have a Major refactor I am currently working on, and do not want to implement it on both main, and then port it to the args branch for its eventual push to main. 

Edit:
Codes been posted in discord. I'll update here when it's implemented and stable on the args branch.

**Comment by Lockszmith-GH** [comment]
Was intersted in this as well, wanted to look at old code too - since developmenty is happening here, posting list to archive code here for future reference: https://github.com/adstanley/truetool-archived

**Comment by heavybullets8** [comment]
The feature is available on the args branch with the sub command `enable`

```
heavyscript enable --help
```

For all the available options.

**Comment by heavybullets8** [comment]
2.0.0 is merged

**Comment by Lockszmith-GH** [comment]
I've been testing this via the args branch, it's working well. I'll test it via main later today.

**Comment by heavybullets8** [comment]
Nothing within the code from `args` to `main`, nor the `2.0.0` version has changed. So it should still work properly. 
Thank you for testing by the way.
