### ISSUE TITLE
Feature: Allow install into non root user

### ISSUE THREAD

**Issue by tyvsmith** [Heavybullets8/heavy_script#94]
To disincentivize allowing root user when not necessary, it'd be great if this script more easily supported use by standard users. Including 1-line deploy script that didn't error if not root and automatic privilege checks/escalation for sudo when necessary.

**Comment by JurgenCruz** [comment]
I actually have this issue. even with sudo I cannot get the installer to run and I don't know/remember the root password to run it with `su`.

**Comment by kleinarne** [comment]
@SuperJugy switching to a root console with `sudo su -` works for me without needing the root password.

**Comment by heavybullets8** [comment]
I need your guys' feedback on the implementation prior to me pushing the changes to main. 

If you already have heavyscript installed, you can just change branch, otherwise go with the installation, both methods will REQUIRE you to switch to the `permissions` branch.

### Installation
> The one liner below uses the new branch, which contains the new implementation, this will allow you to install into a non-root user
```bash
curl -s https://raw.githubusercontent.com/Heavybullets8/heavy_script/permissions/functions/deploy.sh | bash && source "$HOME/.bashrc" 2>/dev/null && source "$HOME/.zshrc" 2>/dev/null
```

### Changing Branches
```bash
heavyscript git --branch
```
> Select the `Permissions` branch

### Changes Made
#### Changes to `/bin/heavyscript`

1. Check if the script is being run with root privileges (`sudo`). If so, look for the `heavy_script` directory in the home directory of the user who invoked `sudo`.
  
2. If the script is not being run with `sudo`, or if the `heavy_script` directory is not found in the first step, then look for the `heavy_script` directory in the current user's home directory.
  
3. If the `heavy_script` directory is not found in either of the above locations, use a custom `find_script_dir` function to search all user-created directories for the `heavy_script` directory.

> The seemingly convoluted search is due to the wrapper script not knowing where `heavy_script` was originally installed. However, it is most likely to be in one of the first two locations mentioned.


#### Changes to `functions/deploy.sh`
1. Allow users to install with non-root users
2. Create symbolic links to both `/usr/local/bin` as well as the users bin `$HOME/bin`
> Both symbolic links are unfortunately required to allow both the sudo users, and the user who installed the script to be able to view it in their $PATH environment. As you guys know, the sudoers $PATH is reset on each upgrade of Truenas SCALE



#### Changes to `heavy_script.sh`
- A new function, `check_root`, is added to determine if root access is required for specific commands (e.g., `update`, `dns`). Most `heavy_script` functions require root access.
    - If the user just wants the help page, it is displayed without needing root.
    - Otherwise, the script exits with an error message stating that root privileges are required.
  
- A second function, `ensure_symlink`, makes sure a symbolic link is present in `/usr/local/bin/heavyscript`.
    - If missing, a warning is displayed suggesting the script be run as `sudo`.
    - Cron jobs, assumed to be a common use-case, require root and the symbolic link is wiped with each TrueNAS SCALE update, thankfully the cron job should re-establish the symbolic link, so hopefully no user interaction is actually required for those of you, who use cron jobs frequently. 



#### New Permissions File: `utils/permissions.sh`
- Contains both the `check_root` and `ensure_symlink` functions.
